export type CompanyRanking = {
  rank: string;
  company: string;
  salary: number;
  chill: number;
  工作強度: number;
  hours: number;
  n: number;
  tag: string;
  tone: "lime" | "blue" | "violet" | "plain";
  logo?: string;
};

const companyAliases: Record<string, string> = {
  synopsys: "Synopsys 新思科技",
  synopsis: "Synopsys 新思科技",
  "synopsys 新思": "Synopsys 新思科技",
  新思科技: "Synopsys 新思科技",
  google: "Google 谷歌",
  微軟: "Microsoft 微軟",
  中華電信: "Chunghwa Telecom 中華電信",
  中華電信股份有限公司: "Chunghwa Telecom 中華電信",
  中華電信研究所: "Chunghwa Telecom 中華電信",
  cht: "Chunghwa Telecom 中華電信",
  gogox: "GOGOX 高高客",
  appier: "Appier 沛星互動科技",
  工研院: "ITRI 工業技術研究院",
  緯創軟體: "Wistron ITS 緯創軟體",
  台灣大哥大: "Taiwan Mobile 台灣大哥大",
  kkcompany: "KKCompany 科科科技",
  將來銀行: "NEXT BANK 將來銀行",
  奧義智慧: "CyCraft 奧義智慧",
  ibm: "IBM 國際商業機器",
  精誠資訊: "SYSTEX 精誠資訊",
  遠傳: "Far EasTone 遠傳電信",
  訊連科技: "CyberLink 訊連科技",
  cyberlink: "CyberLink 訊連科技",
  玉山銀行: "E.SUN Bank 玉山銀行",
  國泰世華: "Cathay United Bank 國泰世華銀行",
  天堂遊戲: "Heaven Games 天堂遊戲",
  昕力資訊: "TPIsoftware 昕力資訊",
  德義資訊: "DEInfo 德義資訊",
  "91app": "91APP 九易宇軒",
  東森購物: "Eastern Home Shopping 東森購物",
  pinkoi: "Pinkoi 果翼科技",
  叡揚資訊: "Galaxy Software Services 叡揚資訊",
  遊戲橘子: "Gamania 遊戲橘子",
  "trend micro": "Trend Micro 趨勢科技",
  趨勢科技: "Trend Micro 趨勢科技",
  趨勢: "Trend Micro 趨勢科技",
  synology: "Synology 群暉科技",
  群暉: "Synology 群暉科技",
  群暉科技: "Synology 群暉科技",
  沛星: "Appier 沛星互動科技",
  國泰: "Cathay United Bank 國泰世華銀行",
  國泰世華銀行: "Cathay United Bank 國泰世華銀行",
  國泰世華銀行股份有限公司: "Cathay United Bank 國泰世華銀行",
  "cathay united bank 國泰世華銀行": "Cathay United Bank 國泰世華銀行",
  玉山: "E.SUN Bank 玉山銀行",
  昕力: "TPIsoftware 昕力資訊",
  精誠: "SYSTEX 精誠資訊",
  叡揚: "Galaxy Software Services 叡揚資訊",
  訊連: "CyberLink 訊連科技",
  訊連科技股份有限公司: "CyberLink 訊連科技",
  谷歌: "Google 谷歌",
  中華電信研究院: "Chunghwa Telecom 中華電信",
  遠傳電信: "Far EasTone 遠傳電信",
  資拓: "資拓宏宇",
  tsmc: "TSMC 台灣積體電路製造",
  台積電: "TSMC 台灣積體電路製造",
  cmoney: "CMoney",
  shopline: "SHOPLINE 商線科技",
  奧義智慧科技股份有限公司: "CyCraft 奧義智慧",
  奧義智慧科技: "CyCraft 奧義智慧",
  txone: "TXOne Networks 睿控網安",
  "txone networks": "TXOne Networks 睿控網安",
  "txone network": "TXOne Networks 睿控網安",
  "txone networks   睿控網安": "TXOne Networks 睿控網安",
  itri: "ITRI 工業技術研究院",
  工業技術研究院: "ITRI 工業技術研究院",
  viewsonic: "ViewSonic 優派國際",
  cadence: "Cadence 益華電腦",
  益華電腦: "Cadence 益華電腦",
  supermicro: "Supermicro 美超微",
  美超微: "Supermicro 美超微",
  dcard: "Dcard 狄卡",
  三竹: "Mitake 三竹資訊",
  三竹資訊: "Mitake 三竹資訊",
  三竹資訊股份有限公司: "Mitake 三竹資訊",
  鴻海: "Hon Hai 鴻海精密工業",
  鴻海精密工業: "Hon Hai 鴻海精密工業",
  普鴻資訊: "Provision Information 普鴻資訊",
};

export function normalizeCompanyName(name: string) {
  const trimmed = name.trim();
  return companyAliases[trimmed.toLocaleLowerCase("en-US")] ?? companyAliases[trimmed] ?? trimmed;
}

export const companyRankings: CompanyRanking[] = [
  { rank: "01", company: "Google 谷歌", salary: 350, chill: 3, 工作強度: 3, hours: 8, n: 9, tag: "薪資中位數居前", tone: "blue", logo: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Google%202026%20logo.svg" },
  { rank: "02", company: "Synopsys 新思科技", salary: 240, chill: 4, 工作強度: 2, hours: 8, n: 11, tag: "高薪、負荷較低", tone: "lime", logo: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Synopsys%20Logo.svg" },
  { rank: "03", company: "TSMC 台灣積體電路製造", salary: 390, chill: 2, 工作強度: 5, hours: 9, n: 6, tag: "高薪、強度 5/5", tone: "violet", logo: "images/tsmc-wordmark.svg" },
  { rank: "04", company: "Microsoft 微軟", salary: 245, chill: 4, 工作強度: 4, hours: 8, n: 7, tag: "高薪、爽度 4/5", tone: "plain" },
  { rank: "05", company: "Chunghwa Telecom 中華電信", salary: 145, chill: 5, 工作強度: 2, hours: 8, n: 11, tag: "爽度 5/5", tone: "plain" },
  { rank: "06", company: "GOGOX 高高客", salary: 176, chill: 3, 工作強度: 3, hours: 8, n: 3, tag: "各項接近中間", tone: "plain" },
  { rank: "07", company: "Appier 沛星互動科技", salary: 175, chill: 3, 工作強度: 4, hours: 9, n: 8, tag: "高薪、強度 4/5", tone: "plain" },
  { rank: "08", company: "ITRI 工業技術研究院", salary: 160, chill: 3, 工作強度: 3, hours: 9, n: 7, tag: "中位數 160 萬", tone: "plain" },
  { rank: "09", company: "Synology 群暉科技", salary: 160, chill: 3, 工作強度: 4, hours: 8, n: 13, tag: "樣本較穩定", tone: "plain" },
  { rank: "10", company: "SHOPLINE 商線科技", salary: 120, chill: 4, 工作強度: 3, hours: 8, n: 3, tag: "體驗均衡", tone: "plain" },
  { rank: "11", company: "Wistron ITS 緯創軟體", salary: 86, chill: 3.5, 工作強度: 2, hours: 8, n: 8, tag: "負荷較低", tone: "plain" },
  { rank: "12", company: "Trend Micro 趨勢科技", salary: 120, chill: 3, 工作強度: 3, hours: 8, n: 26, tag: "高可信度樣本", tone: "plain" },
  { rank: "13", company: "Taiwan Mobile 台灣大哥大", salary: 100, chill: 4, 工作強度: 3, hours: 8, n: 3, tag: "體驗均衡", tone: "plain" },
  { rank: "14", company: "KKCompany 科科科技", salary: 95, chill: 4, 工作強度: 3, hours: 6, n: 3, tag: "工時友善", tone: "plain" },
  { rank: "15", company: "Hon Hai 鴻海精密工業", salary: 108, chill: 4, 工作強度: 3, hours: 8, n: 3, tag: "硬體科技", tone: "plain" },
  { rank: "16", company: "ViewSonic 優派國際", salary: 84, chill: 4, 工作強度: 3, hours: 8, n: 3, tag: "體驗均衡", tone: "plain" },
  { rank: "17", company: "NEXT BANK 將來銀行", salary: 120, chill: 3, 工作強度: 3.5, hours: 9, n: 4, tag: "金融科技", tone: "plain" },
  { rank: "18", company: "CyCraft 奧義智慧", salary: 120, chill: 2.5, 工作強度: 3, hours: 8, n: 4, tag: "資安職涯", tone: "plain" },
  { rank: "19", company: "IBM 國際商業機器", salary: 150, chill: 2, 工作強度: 4, hours: 9, n: 7, tag: "高薪、強度 4/5", tone: "plain" },
  { rank: "20", company: "SYSTEX 精誠資訊", salary: 59.9, chill: 3.5, 工作強度: 3, hours: 8, n: 8, tag: "體驗均衡", tone: "plain" },
  { rank: "21", company: "Far EasTone 遠傳電信", salary: 104, chill: 3, 工作強度: 3, hours: 8, n: 3, tag: "均衡型", tone: "plain" },
  { rank: "22", company: "CyberLink 訊連科技", salary: 115, chill: 3, 工作強度: 3, hours: 8, n: 9, tag: "體驗均衡", tone: "plain" },
  { rank: "23", company: "Provision Information 普鴻資訊", salary: 77, chill: 4, 工作強度: 3, hours: 8, n: 3, tag: "金融資訊", tone: "plain" },
  { rank: "24", company: "E.SUN Bank 玉山銀行", salary: 80, chill: 3, 工作強度: 3, hours: 8.2, n: 9, tag: "樣本較穩定", tone: "plain" },
  { rank: "25", company: "Cathay United Bank 國泰世華銀行", salary: 103.6, chill: 3, 工作強度: 3, hours: 8, n: 10, tag: "金融職涯", tone: "plain" },
  { rank: "26", company: "Heaven Games 天堂遊戲", salary: 96, chill: 3, 工作強度: 3, hours: 8, n: 3, tag: "遊戲產業", tone: "plain" },
  { rank: "27", company: "TPIsoftware 昕力資訊", salary: 73.5, chill: 3.5, 工作強度: 2.5, hours: 8, n: 12, tag: "樣本較穩定", tone: "plain" },
  { rank: "28", company: "DEInfo 德義資訊", salary: 62, chill: 3, 工作強度: 2, hours: 8, n: 3, tag: "負荷較低", tone: "plain" },
  { rank: "29", company: "91APP 九易宇軒", salary: 124, chill: 2, 工作強度: 4, hours: 8, n: 3, tag: "薪資優勢", tone: "plain" },
  { rank: "30", company: "Eastern Home Shopping 東森購物", salary: 65, chill: 2, 工作強度: 3, hours: 8.5, n: 3, tag: "電商產業", tone: "plain" },
  { rank: "31", company: "Pinkoi 果翼科技", salary: 85, chill: 2, 工作強度: 4, hours: 9, n: 3, tag: "產品職涯", tone: "plain" },
  { rank: "32", company: "TXOne Networks 睿控網安", salary: 113.5, chill: 1, 工作強度: 4.5, hours: 8, n: 6, tag: "強度 4.5/5", tone: "plain" },
  { rank: "33", company: "Galaxy Software Services 叡揚資訊", salary: 56, chill: 2, 工作強度: 3.5, hours: 8.25, n: 6, tag: "企業軟體", tone: "plain" },
  { rank: "34", company: "Gamania 遊戲橘子", salary: 86.7, chill: 2, 工作強度: 3.5, hours: 8, n: 6, tag: "遊戲產業", tone: "plain" },
  { rank: "35", company: "Mitake 三竹資訊", salary: 84, chill: 3, 工作強度: 4, hours: 8, n: 3, tag: "通訊軟體", tone: "plain" },
];
